# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files into container
RUN pip install Flask flask-cors
COPY . .

# Expose Flask port
EXPOSE 8000

# Run the app
CMD ["python", "app.py"]
